export const PAGE_LEVEL_ERROR_OCCURED = "PAGE_LEVEL_ERROR_OCCURED";

export const SEARCH_CHARACTER_REQUESTED = "SEARCH_CHARACTER_REQUESTED";
export const SEARCH_CHARACTER_FULFILLED = "SEARCH_CHARACTER_FULFILLED";

export const UPDATE_SELECTED_CHARACTER_INDEX = "UPDATE_SELECTED_CHARACTER_INDEX";

export const FETCH_ONE_PORTAL_HOME_DATA = "FETCH_ONE_PORTAL_HOME_DATA";
export const FETCH_ONE_PORTAL_HOME_DATA_FULFILLED = "FETCH_ONE_PORTAL_HOME_DATA_FULFILLED";
export const SET_PAGE_TYPE = "SET_PAGE_TYPE";

// IRS Exception Action Types
export const FETCH_ONE_PORTAL_IRS_EXCEPTIONS_DATA = "FETCH_ONE_PORTAL_IRS_EXCEPTIONS_DATA";
export const FETCH_ONE_PORTAL_IRS_EXCEPTIONS_DATA_FULFILLED = "FETCH_ONE_PORTAL_IRS_EXCEPTIONS_DATA_FULFILLED";
export const SUBSTANTIATE_ONE_PORTAL_IRS_EXCEPTIONS = "SUBSTANTIATE_ONE_PORTAL_IRS_EXCEPTIONS";
export const SUBSTANTIATE_ONE_PORTAL_IRS_EXCEPTIONS_FULFILLED = "SUBSTANTIATE_ONE_PORTAL_IRS_EXCEPTIONS_FULFILLED";
export const UPDATE_EXPLANATION_OPTION = "UPDATE_EXPLANATION_OPTION";
export const UPDATE_WRITTEN_EXPLANATION_FREE_FORM = "UPDATE_WRITTEN_EXPLANATION_FREE_FORM";
export const UPDATE_WRITTEN_EXPLANATION = "UPDATE_WRITTEN_EXPLANATION";
export const UPDATE_NO_OF_DAYS_IN_CURRENT_YEAR = "UPDATE_NO_OF_DAYS_IN_CURRENT_YEAR";
export const UPDATE_NO_OF_DAYS_IN_FIRST_PRIOR_YEAR = "UPDATE_NO_OF_DAYS_IN_FIRST_PRIOR_YEAR";
export const UPDATE_NO_OF_DAYS_IN_SECOND_PRIOR_YEAR = "UPDATE_NO_OF_DAYS_IN_SECOND_PRIOR_YEAR";
export const UPDATE_MAIN_DOCUMENT_TYPE = "UPDATE_MAIN_DOCUMENT_TYPE";
export const UPDATE_MAIN_DOCUMENT_FILE = "UPDATE_MAIN_DOCUMENT_FILE";
export const UPDATE_IS_NAME_MISMATCH_DOCUMENT_VISIBLE = "UPDATE_IS_NAME_MISMATCH_DOCUMENT_VISIBLE";
export const UPDATE_NAME_MISMATCH_DOCUMENT_TYPE = "UPDATE_NAME_MISMATCH_DOCUMENT_TYPE";
export const UPDATE_NAME_MISMATCH_DOCUMENT_FILE = "UPDATE_NAME_MISMATCH_DOCUMENT_FILE";
export const UPDATE_IS_UPLOADED_DOC_EXPIRED_DOCUMENT_VISIBLE = "UPDATE_IS_UPLOADED_DOC_EXPIRED_DOCUMENT_VISIBLE";
export const UPDATE_UPLOADED_DOC_EXPIRED_DOCUMENT_TYPE = "UPDATE_UPLOADED_DOC_EXPIRED_DOCUMENT_TYPE";
export const UPDATE_UPLOADED_DOC_EXPIRED_DOCUMENT_FILE = "UPDATE_UPLOADED_DOC_EXPIRED_DOCUMENT_FILE";
export const UPDATE_IS_SUBSTANTIAL_PRESENCE_TEST_PASSED = "UPDATE_IS_SUBSTANTIAL_PRESENCE_TEST_PASSED";
export const UPDATE_DOCUMENT_UPLOAD_OR_WRITTEN_EXPLANATION = "UPDATE_DOCUMENT_UPLOAD_OR_WRITTEN_EXPLANATION";
export const RESET_IRS_EXCEPTIONS_VALUES = "RESET_IRS_EXCEPTIONS_VALUES";
export const STORE_EXPLANATION_REASONS_CSS_PROPERTIES = "STORE_EXPLANATION_REASONS_CSS_PROPERTIES";
export const STORE_DOCUMENT_UPLOAD_ONLY_CSS_PROPERTIES = "STORE_DOCUMENT_UPLOAD_ONLY_CSS_PROPERTIES";
export const STORE_SUBSTANTIAL_PRESENCE_TEST_FAILED_CSS_PROPERTIES =
  "STORE_SUBSTANTIAL_PRESENCE_TEST_FAILED_CSS_PROPERTIES";
export const SET_EXPLANATION_REASONS_PREFILLED_STATE = "SET_EXPLANATION_REASONS_PREFILLED_STATE";
export const UPDATE_SHOULD_PREFILL_MAIN_DOCUMENT_DATA = "UPDATE_SHOULD_PREFILL_MAIN_DOCUMENT_DATA";
export const SET_MAIN_DOCUMENT_PREFILLED_STATE = "SET_MAIN_DOCUMENT_PREFILLED_STATE";
export const SET_NAME_MISMATCH_DOCUMENT_PREFILLED_STATE = "SET_NAME_MISMATCH_DOCUMENT_PREFILLED_STATE";
export const SET_UPLOADED_DOC_EXPIRED_DOCUMENT_PREFILLED_STATE = "SET_UPLOADED_DOC_EXPIRED_DOCUMENT_PREFILLED_STATE";
export const UPDATE_EDELIVERY_CONSENT_REQUESTED = "UPDATE_EDELIVERY_CONSENT_REQUESTED";
export const UPDATE_EDELIVERY_CONSENT_FULFILLED = "UPDATE_EDELIVERY_CONSENT_FULFILLED";
